# Generated by Django 5.1.6 on 2025-02-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=5000)),
                ('content', models.TextField()),
                ('example_problem', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
